const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,dashboard:null,projects:[],tasks:[],allTasks:[],meetings:[],budget:[],notifications:[],daily:[],users:[],alfaSchedule:[],workload:[],selectedProject:null,selectedWorkload:null,projectFilter:'All',taskFilter:'All',meetingFilter:'All',scheduleFilter:'Today',workloadFilter:'All'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pad2=n=>String(n).padStart(2,'0');
const localDateKey=d=>`${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`;
const todayKey=()=>localDateKey(new Date());
const dateKey=v=>{if(!v)return'';if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v.slice(0,10)))return v.slice(0,10);const d=new Date(v);return isNaN(d)?String(v).slice(0,10):localDateKey(d)};
const timeKey=v=>{if(!v)return'';const raw=String(v);const m=raw.match(/^(\d{1,2}):(\d{2})/);if(m)return `${pad2(m[1])}:${m[2]}`;const d=new Date(v);return isNaN(d)?raw.slice(0,5):`${pad2(d.getHours())}:${pad2(d.getMinutes())}`};
const fmtDate=v=>{if(!v)return'-';const key=dateKey(v),m=key.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(m){const d=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));return d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'})}return String(v)};
const fmtTime=v=>timeKey(v)||'-';
const fmtMoney=v=>'Rp '+Number(v||0).toLocaleString('id-ID');
const isOverdue=t=>t.deadline&&t.status!=='Completed'&&dateKey(t.deadline)<todayKey();
const roleUpper=()=>String(state.user?.role||'').toUpperCase();
const canManage=()=>['PM','ADMIN','LEADER','OWNER','CEO','Talent Support','Talent Support','Business Unit Admin'].some(r=>roleUpper().includes(r));
const canAdmin=()=>['ADMIN','LEADER','OWNER','CEO'].some(r=>roleUpper().includes(r));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.add('hidden'),2200)}
function empty(t){return `<div class="empty"><span class="muted">${esc(t)}</span></div>`}
function option(value,label,selected){return `<option value="${esc(value)}" ${String(value)===String(selected)?'selected':''}>${esc(label??value)}</option>`}
function projectOptions(selected=''){return state.projects.map(p=>option(p.projectId,`${p.projectName} · ${p.clientCompany||''}`,selected)).join('')}
function userOptions(selected=''){const src=state.users.length?state.users:[{name:'MIMO'},{name:'Ibnu'},{name:'Rossy'},{name:'Adel'},{name:'Nay'},{name:'Om Agung'},{name:'Eki'},{name:'Pak Alfa'}];return src.filter(u=>String(u.active)!=='false').map(u=>option(u.name,u.name,selected)).join('')}
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.bottom-nav [data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='notifications')renderNotifications();if(page==='activity')renderActivity();if(page==='users')renderUsers();if(page==='workload')renderWorkload();if(page==='workloadDetail')renderWorkloadDetail();}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function onlineState(){const off=!navigator.onLine;$('#offlineBar').classList.toggle('hidden',!off)}
window.addEventListener('online',()=>{onlineState();toast('Kembali online')});window.addEventListener('offline',onlineState);onlineState();

async function boot(){if(!APP_CONFIG.API_URL.startsWith('http'))return;const token=localStorage.getItem(APP_CONFIG.TOKEN_KEY);if(!token)return;try{state.user=await API.call('getCurrentUser');await enterApp()}catch(e){localStorage.removeItem(APP_CONFIG.TOKEN_KEY)}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='Memeriksa...';try{const d=await API.call('authenticateUser',{email:$('#email').value.trim(),password:$('#password').value});localStorage.setItem(APP_CONFIG.TOKEN_KEY,d.token);state.user=d.user;await enterApp()}catch(err){$('#loginMsg').textContent='Login gagal: '+err.message}};
$('#logoutBtn').onclick=async()=>{try{await API.call('logout')}catch(e){}localStorage.removeItem(APP_CONFIG.TOKEN_KEY);location.reload()};
$('#notifBtn').onclick=()=>go('notifications');
async function enterApp(){ $('#loginView').classList.add('hidden');$('#mainView').classList.remove('hidden');$('#welcomeText').textContent='Halo, '+state.user.name;$('#userRole').textContent=state.user.role;$('#usersMenuBtn').style.display=canAdmin()?'block':'none';$('#workloadMenuBtn').style.display=canManage()?'block':'none';$('#newProjectBtn').style.display=canManage()?'inline-block':'none';$('#newTaskBtn').style.display=canManage()?'inline-block':'none';$('#newMeetingBtn').style.display=canManage()?'inline-block':'none';$('#newBudgetBtn').style.display=canManage()?'inline-block':'none';$('#newUserBtn').style.display=canAdmin()?'inline-block':'none';await refreshAll(); }
async function refreshAll(){try{const req=[API.call('getDashboard'),API.call('getProjects'),API.call('getMyTasks'),API.call('getMeetings'),API.call('getBudget'),API.call('getNotifications')];if(canManage())req.push(API.call('getTasks'));else req.push(Promise.resolve([]));if(canManage())req.push(API.call('getUsers'));else req.push(Promise.resolve([]));req.push(API.call('getDailyUpdates'));req.push(API.call('getAlfaSchedule'));req.push(canManage()?API.call('getWorkload'):Promise.resolve([]));[state.dashboard,state.projects,state.tasks,state.meetings,state.budget,state.notifications,state.allTasks,state.users,state.daily,state.alfaSchedule,state.workload]=await Promise.all(req);render()}catch(e){alert('Gagal memuat data: '+e.message)}}
function render(){renderMetrics();renderProjects();renderTasks();renderMeetings();renderBudget();renderDaily();renderSchedule();renderNotifications();renderUsers();if(canManage())renderWorkload();if(state.selectedProject)renderProjectDetail();if(state.selectedWorkload)renderWorkloadDetail()}
function renderMetrics(){const d=state.dashboard||{};const items=[['Project',d.totalProjects||0],['My Tasks',d.myTasks||0],['Overdue',d.overdueTasks||0,true],['MOM Pending',d.momPending||0,true],['Meeting Hari Ini',d.todayMeetings||0],['Blocked',d.blockedTasks||0,true],['Budget Alert',d.budgetAlerts||0,true],['Project Risk',d.atRiskProjects||0,true]];$('#metrics').innerHTML=items.map(x=>`<div class="metric ${x[2]&&x[1]>0?'attn':''}"><span>${esc(x[0])}</span><br><strong>${x[1]}</strong></div>`).join('');$('#homeTasks').innerHTML=state.tasks.filter(t=>t.status!=='Completed').slice(0,4).map(taskCard).join('')||empty('Belum ada task.');$('#todayMeetings').innerHTML=state.meetings.filter(m=>dateKey(m.date)===todayKey()).sort(sortMeeting).map(meetingCard).join('')||empty('Tidak ada meeting hari ini.');$('#notifCount').textContent=state.notifications.length}
function projectCard(p){const tasks=(state.allTasks.length?state.allTasks:state.tasks).filter(t=>t.projectId===p.projectId), done=tasks.filter(t=>t.status==='Completed').length, progress=tasks.length?Math.round(done/tasks.length*100):0;return `<div class="card clickable ${tasks.some(isOverdue)?'attn':''}" data-project="${esc(p.projectId)}"><div class="row"><div><strong>${esc(p.projectName)}</strong><div class="muted">${esc(p.clientCompany)} · ${esc(p.brand)}</div></div><span class="badge ${p.projectStatus==='On Progress'?'yellow':''}">${esc(p.projectStatus)}</span></div><p class="muted">${esc(p.projectType)} · PM ${esc(p.pm||'-')}</p><div class="progress"><span style="width:${progress}%"></span></div><div class="muted">${tasks.length} task · ${progress}% complete</div></div>`}
function renderProjects(){const q=($('#projectSearch').value||'').toLowerCase(), filters=['All','Upcoming Pitching','Upcoming Project','Ongoing Project','Completed'];$('#projectFilters').innerHTML=filters.map(x=>`<button class="chip ${state.projectFilter===x?'active':''}" data-project-filter="${x}">${x}</button>`).join('');$$('[data-project-filter]').forEach(b=>b.onclick=()=>{state.projectFilter=b.dataset.projectFilter;renderProjects()});let arr=state.projects.filter(p=>JSON.stringify(p).toLowerCase().includes(q));if(state.projectFilter!=='All')arr=arr.filter(p=>p.projectType===state.projectFilter||p.projectStatus===state.projectFilter);$('#projectList').innerHTML=arr.map(projectCard).join('')||empty('Project belum ada.');$$('[data-project]').forEach(c=>c.onclick=()=>openProject(c.dataset.project))}
$('#projectSearch').oninput=renderProjects;
setTimeout(()=>{const x=$('#workloadSearch');if(x)x.oninput=renderWorkload},0);
function openProject(id){state.selectedProject=state.projects.find(p=>p.projectId===id)||null;if(state.selectedProject){renderProjectDetail();go('projectDetail')}}
function renderProjectDetail(){const p=state.selectedProject;if(!p)return;const all=state.allTasks.length?state.allTasks:state.tasks, tasks=all.filter(t=>t.projectId===p.projectId), meetings=state.meetings.filter(m=>m.projectId===p.projectId), budget=state.budget.find(b=>b.projectId===p.projectId),done=tasks.filter(t=>t.status==='Completed').length,progress=tasks.length?Math.round(done/tasks.length*100):0;$('#projectDetail').innerHTML=`<div class="kicker">${esc(p.projectId)} · ${esc(p.projectType)}</div><h1 class="project-title">${esc(p.projectName)}</h1><div class="muted">${esc(p.clientCompany)} · ${esc(p.brand||'')}</div><div class="detail-grid"><div class="detail-item"><small>PM</small><strong>${esc(p.pm||'-')}</strong></div><div class="detail-item"><small>Status</small><strong>${esc(p.projectStatus||'-')}</strong></div><div class="detail-item"><small>Timeline</small><strong>${fmtDate(p.startDate)} — ${fmtDate(p.endDate)}</strong></div><div class="detail-item"><small>Progress</small><strong>${progress}%</strong></div></div>${p.driveFolder?`<p><a class="link" href="${esc(p.driveFolder)}" target="_blank" rel="noopener">Buka Google Drive Project ↗</a></p>`:''}<div class="tabs"><button class="tab active">Tasks ${tasks.length}</button><button class="tab">Meetings ${meetings.length}</button><button class="tab">Budget</button></div><div class="section-head"><h3>Tasks</h3><button class="btn primary small" data-add-task-project="${esc(p.projectId)}">+ Task</button></div><div class="stack">${tasks.map(taskCard).join('')||empty('Belum ada task.')}</div><div class="section-head"><h3>Meetings</h3><button class="btn primary small" data-add-meeting-project="${esc(p.projectId)}">+ Meeting</button></div><div class="stack">${meetings.map(meetingCard).join('')||empty('Belum ada meeting.')}</div><div class="section-head"><h3>Budget</h3>${canManage()?`<button class="btn primary small" data-budget-project="${esc(p.projectId)}">Update</button>`:''}</div>${budget?budgetCard(budget):empty('Budget belum diisi.')}`;bindDynamicActions()}
function taskCard(t){const overdue=isOverdue(t);return `<div class="card ${overdue?'attn':''}"><div class="row"><div><strong>${esc(t.taskName)}</strong><div class="muted">${esc(t.projectName)}</div></div><span class="badge ${overdue||t.status==='Blocked'?'yellow':''}">${overdue?'OVERDUE':esc(t.status)}</span></div><div class="muted">PIC ${esc(t.pic)} · Deadline ${fmtDate(t.deadline)} · ${Number(t.progress||0)}%</div><div class="progress"><span style="width:${Math.max(0,Math.min(100,Number(t.progress||0)))}%"></span></div>${t.nextAction?`<p><strong>Next:</strong> ${esc(t.nextAction)}</p>`:''}${t.blocker?`<div class="summary-box"><strong>Blocker:</strong> ${esc(t.blocker)}</div>`:''}<div class="card-actions"><button class="btn primary small" data-edit-task="${esc(t.taskId)}">Update Task</button>${t.fileLink?`<a class="btn small link" href="${esc(t.fileLink)}" target="_blank" rel="noopener">File ↗</a>`:''}</div></div>`}
function renderTasks(){const filters=['All','Today','Overdue','On Progress','Waiting','Blocked','Completed'];$('#taskFilters').innerHTML=filters.map(x=>`<button class="chip ${state.taskFilter===x?'active':''}" data-task-filter="${x}">${x}</button>`).join('');$$('[data-task-filter]').forEach(b=>b.onclick=()=>{state.taskFilter=b.dataset.taskFilter;renderTasks()});let a=state.tasks;if(state.taskFilter==='Overdue')a=a.filter(isOverdue);else if(state.taskFilter==='Today')a=a.filter(t=>dateKey(t.deadline)===todayKey());else if(state.taskFilter!=='All')a=a.filter(t=>t.status===state.taskFilter);$('#taskList').innerHTML=a.map(taskCard).join('')||empty('Tidak ada task.');bindDynamicActions()}
function sortMeeting(a,b){return String(dateKey(a.date)+' '+timeKey(a.startTime)).localeCompare(String(dateKey(b.date)+' '+timeKey(b.startTime)))}
function meetingCard(m){const cancelled=m.status==='Cancelled',done=m.momStatus==='Done',pending=m.momStatus==='Pending';return `<div class="card meeting-card ${pending?'attn':''}"><div class="row"><div class="meeting-title-wrap"><span class="meeting-time">${esc(fmtTime(m.startTime))}</span><div><strong>${esc(m.title)}</strong><div class="muted">${esc(m.projectName)} · ${esc(m.location||'-')}</div></div></div><span class="badge ${pending?'yellow':''}">${esc(m.status||'Scheduled')}</span></div><p class="muted">${fmtDate(m.date)} · ${esc(m.participants||'Belum ada participant')}</p>${m.agenda?`<p>${esc(m.agenda)}</p>`:''}<div class="meeting-meta"><span class="badge ${pending?'yellow':''}">MOM ${esc(m.momStatus||'Waiting')}</span>${String(m.alfaRequired).toLowerCase()==='true'?'<span class="badge yellow">ALFA REQUIRED</span>':''}</div><div class="card-actions">${pending?`<button class="btn primary small" data-create-mom="${esc(m.meetingId)}">Buat MOM</button>`:done?`<button class="btn small" data-view-mom="${esc(m.meetingId)}">Lihat MOM</button>`:(!cancelled&&canManage()?`<button class="btn primary small" data-complete-meeting="${esc(m.meetingId)}">Selesai → MOM</button>`:'')}${canManage()&&!cancelled?`<button class="btn small" data-edit-meeting="${esc(m.meetingId)}">Edit / Reschedule</button><button class="btn small" data-cancel-meeting="${esc(m.meetingId)}">Cancel</button>`:''}</div></div>`}
function renderMeetings(){const fs=['All','Today','MOM Pending'];$('#meetingFilters').innerHTML=fs.map(x=>`<button class="chip ${state.meetingFilter===x?'active':''}" data-meeting-filter="${x}">${x}</button>`).join('');$$('[data-meeting-filter]').forEach(b=>b.onclick=()=>{state.meetingFilter=b.dataset.meetingFilter;renderMeetings()});let a=[...state.meetings].sort(sortMeeting);if(state.meetingFilter==='Today')a=a.filter(m=>dateKey(m.date)===todayKey());if(state.meetingFilter==='MOM Pending')a=a.filter(m=>m.momStatus==='Pending');$('#meetingList').innerHTML=a.map(meetingCard).join('')||empty('Belum ada meeting.');bindDynamicActions()}
function budgetCard(b){return `<div class="card ${['ALERT','OVER BUDGET'].includes(b.budgetStatus)?'attn':''}"><div class="row"><strong>${esc(b.projectName)}</strong><span class="badge ${b.budgetStatus!=='SAFE'?'yellow':''}">${esc(b.budgetStatus)}</span></div><div class="detail-grid"><div class="detail-item"><small>Approved</small><strong>${fmtMoney(b.approvedQuotation)}</strong></div><div class="detail-item"><small>Planned</small><strong>${fmtMoney(b.plannedCosting)}</strong></div><div class="detail-item"><small>Actual</small><strong>${fmtMoney(b.actualCosting)}</strong></div><div class="detail-item"><small>Remaining</small><strong>${fmtMoney(b.remainingBudget)}</strong></div></div><div class="progress"><span style="width:${Math.min(100,Number(b.budgetUsagePercent||0))}%"></span></div><div class="muted">Usage ${Number(b.budgetUsagePercent||0).toFixed(1)}% · Margin ${Number(b.marginPercent||0).toFixed(1)}%</div>${canManage()?`<div class="card-actions"><button class="btn primary small" data-budget-project="${esc(b.projectId)}">Update Budget</button></div>`:''}</div>`}
function renderBudget(){const sum=state.budget.reduce((a,b)=>({approved:a.approved+Number(b.approvedQuotation||0),planned:a.planned+Number(b.plannedCosting||0),actual:a.actual+Number(b.actualCosting||0),alert:a.alert+(['ALERT','OVER BUDGET'].includes(b.budgetStatus)?1:0)}),{approved:0,planned:0,actual:0,alert:0});$('#budgetSummary').innerHTML=[['Approved',fmtMoney(sum.approved)],['Planned',fmtMoney(sum.planned)],['Actual',fmtMoney(sum.actual)],['Alert',sum.alert]].map(x=>`<div class="metric ${x[0]==='Alert'&&x[1]?'attn':''}"><span>${x[0]}</span><br><strong style="font-size:18px">${x[1]}</strong></div>`).join('');$('#budgetList').innerHTML=state.budget.map(budgetCard).join('')||empty('Budget belum ada.');bindDynamicActions()}
function renderDaily(){$('#dailyList').innerHTML=state.daily.slice().reverse().slice(0,80).map(x=>`<div class="card"><div class="row"><strong>${esc(x.pic||x.createdBy)}</strong><span class="badge">${fmtDate(x.date||x.createdAt)}</span></div><div class="muted">${esc(x.projectName||x.projectId||'')} · ${esc(x.taskName||x.taskId||'')}</div><p>${esc(x.update||'')}</p>${x.nextAction?`<p><strong>Next:</strong> ${esc(x.nextAction)}</p>`:''}${x.blocker?`<div class="summary-box"><strong>Blocker:</strong> ${esc(x.blocker)}</div>`:''}</div>`).join('')||empty('Belum ada daily update.')}
async function renderNotifications(){if(!state.user)return;$('#notificationList').innerHTML=state.notifications.map(n=>`<div class="card ${!n.readAt?'attn':''}"><div class="row"><strong>${esc(n.title)}</strong><span class="badge">${esc(n.type)}</span></div><p>${esc(n.message)}</p><div class="card-actions"><button class="btn small" data-read-notif="${esc(n.notificationId)}">Tandai dibaca</button></div></div>`).join('')||empty('Tidak ada notifikasi baru.');$$('[data-read-notif]').forEach(b=>b.onclick=async()=>{await API.call('markNotificationRead',{notificationId:b.dataset.readNotif});state.notifications=await API.call('getNotifications');renderNotifications();$('#notifCount').textContent=state.notifications.length})}
async function renderActivity(){if(!state.user)return;try{const a=await API.call('getActivityLog');$('#activityList').innerHTML=a.slice(0,100).map(x=>`<div class="card"><div class="row"><strong>${esc(x.userName||x.user)}</strong><span class="badge">${esc(x.action)}</span></div><div>${esc(x.description)}</div><span class="muted">${esc(x.timestamp)}</span></div>`).join('')||empty('Belum ada activity.')}catch(e){$('#activityList').innerHTML=empty('Activity belum bisa dimuat.')}}
function inScheduleRange(m,filter){const d=dateKey(m.date),t=todayKey();if(filter==='Today')return d===t;const base=new Date();if(filter==='Tomorrow'){base.setDate(base.getDate()+1);return d===localDateKey(base)}if(filter==='This Week'){const end=new Date();end.setDate(end.getDate()+7);return d>=t&&d<=localDateKey(end)}return true}
function renderSchedule(){const fs=['Today','Tomorrow','This Week'];$('#scheduleFilters').innerHTML=fs.map(x=>`<button class="chip ${state.scheduleFilter===x?'active':''}" data-schedule-filter="${x}">${x}</button>`).join('');$$('[data-schedule-filter]').forEach(b=>b.onclick=()=>{state.scheduleFilter=b.dataset.scheduleFilter;renderSchedule()});const a=(state.alfaSchedule||[]).filter(m=>inScheduleRange(m,state.scheduleFilter)).sort(sortMeeting);$('#scheduleList').innerHTML=a.map(meetingCard).join('')||empty('Tidak ada jadwal Pak Alfa.')}

function workloadStatusLabel(w){
  if(Number(w.blocked||0)>0)return 'BLOCKED';
  if(Number(w.overdue||0)>0)return 'OVERDUE';
  if(Number(w.active||0)>0)return 'ACTIVE';
  return 'CLEAR';
}
function workloadCard(w){
  const attn=Number(w.overdue||0)>0||Number(w.blocked||0)>0;
  return `<div class="card clickable workload-card ${attn?'attn':''}" data-workload-user="${esc(w.userId)}">
    <div class="row">
      <div><strong>${esc(w.name)}</strong><div class="muted">${esc(w.role||'-')}</div></div>
      <span class="badge ${attn?'yellow':''}">${workloadStatusLabel(w)}</span>
    </div>
    <div class="workload-count"><strong>${Number(w.active||0)}</strong><span>active tasks</span></div>
    <div class="workload-stats">
      <span><b>${Number(w.notStarted||0)}</b> Not Started</span>
      <span><b>${Number(w.onProgress||0)}</b> On Progress</span>
      <span><b>${Number(w.waiting||0)}</b> Waiting</span>
      <span><b>${Number(w.blocked||0)}</b> Blocked</span>
      <span><b>${Number(w.overdue||0)}</b> Overdue</span>
    </div>
  </div>`;
}
function renderWorkload(){
  if(!canManage())return;
  const rows=state.workload||[];
  const active=rows.reduce((a,w)=>a+Number(w.active||0),0);
  const overdue=rows.reduce((a,w)=>a+Number(w.overdue||0),0);
  const blocked=rows.reduce((a,w)=>a+Number(w.blocked||0),0);
  const people=rows.filter(w=>Number(w.active||0)>0).length;
  $('#workloadSummary').innerHTML=[
    ['Active Tasks',active],
    ['People Active',people],
    ['Overdue',overdue,true],
    ['Blocked',blocked,true]
  ].map(x=>`<div class="metric ${x[2]&&x[1]>0?'attn':''}"><span>${x[0]}</span><br><strong>${x[1]}</strong></div>`).join('');
  const filters=['All','Has Active','Overdue','Blocked','Clear'];
  $('#workloadFilters').innerHTML=filters.map(x=>`<button class="chip ${state.workloadFilter===x?'active':''}" data-workload-filter="${x}">${x}</button>`).join('');
  $$('[data-workload-filter]').forEach(b=>b.onclick=()=>{state.workloadFilter=b.dataset.workloadFilter;renderWorkload()});
  const q=($('#workloadSearch')?.value||'').toLowerCase();
  let arr=[...rows];
  if(state.workloadFilter==='Has Active')arr=arr.filter(w=>Number(w.active||0)>0);
  if(state.workloadFilter==='Overdue')arr=arr.filter(w=>Number(w.overdue||0)>0);
  if(state.workloadFilter==='Blocked')arr=arr.filter(w=>Number(w.blocked||0)>0);
  if(state.workloadFilter==='Clear')arr=arr.filter(w=>Number(w.active||0)===0);
  if(q)arr=arr.filter(w=>(String(w.name)+' '+String(w.role)).toLowerCase().includes(q));
  arr.sort((a,b)=>Number(b.active||0)-Number(a.active||0)||String(a.name).localeCompare(String(b.name)));
  $('#workloadList').innerHTML=arr.map(workloadCard).join('')||empty('Tidak ada data workload.');
  $$('[data-workload-user]').forEach(c=>c.onclick=()=>openWorkload(c.dataset.workloadUser));
}
function openWorkload(userId){
  state.selectedWorkload=(state.workload||[]).find(w=>String(w.userId)===String(userId))||null;
  if(state.selectedWorkload){renderWorkloadDetail();go('workloadDetail')}
}
function renderWorkloadDetail(){
  const w=state.selectedWorkload;if(!w)return;
  const tasks=(w.tasks||[]);
  const overdue=tasks.filter(t=>t.overdue);
  const blocked=tasks.filter(t=>t.status==='Blocked');
  $('#workloadDetail').innerHTML=`
    <div class="kicker">PERSONAL WORKLOAD</div>
    <h1 class="project-title">${esc(w.name)}</h1>
    <div class="muted">${esc(w.role||'-')}</div>
    <div class="detail-grid">
      <div class="detail-item"><small>Active</small><strong>${Number(w.active||0)}</strong></div>
      <div class="detail-item"><small>On Progress</small><strong>${Number(w.onProgress||0)}</strong></div>
      <div class="detail-item"><small>Overdue</small><strong>${Number(w.overdue||0)}</strong></div>
      <div class="detail-item"><small>Blocked</small><strong>${Number(w.blocked||0)}</strong></div>
    </div>
    ${overdue.length?`<div class="summary-box"><strong>${overdue.length} task overdue.</strong><br><span>Perlu follow up deadline.</span></div>`:''}
    ${blocked.length?`<div class="summary-box" style="margin-top:10px"><strong>${blocked.length} task blocked.</strong><br><span>Cek blocker dan next action.</span></div>`:''}
    <div class="section-head"><h3>Active Tasks</h3><span class="badge">${tasks.length}</span></div>
    <div class="stack">${tasks.map(t=>taskCard(t)).join('')||empty('Tidak ada task aktif.')}</div>`;
  bindDynamicActions();
}

function renderUsers(){if(!canAdmin())return;$('#userList').innerHTML=state.users.map(u=>`<div class="card"><div class="row"><div><strong>${esc(u.name)}</strong><div class="muted">${esc(u.email)}</div></div><span class="badge">${esc(u.role)}</span></div><div class="muted">${String(u.active)==='false'?'Inactive':'Active'}${u.phone?' · '+esc(u.phone):''}</div></div>`).join('')||empty('Belum ada users.')}
function openModal(title,html,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;const dlg=$('#modal'),form=$('#modalForm');form.reset();dlg.showModal();$$('[data-modal-close]').forEach(b=>b.onclick=()=>dlg.close('cancel'));form.onsubmit=async e=>{e.preventDefault();if(e.submitter&&e.submitter.dataset.modalClose!==undefined){dlg.close('cancel');return}const data=Object.fromEntries(new FormData(e.target).entries());try{$('#modalSave').disabled=true;$('#modalSave').textContent='Menyimpan...';await onSave(data,e.target);dlg.close('saved');toast('Tersimpan ✓');await refreshAll()}catch(err){alert(err.message)}finally{$('#modalSave').disabled=false;$('#modalSave').textContent='Simpan'}}}
function field(label,name,type='text',value='',opts={}){if(type==='select')return `<label class="${opts.full?'full':''}">${label}<select name="${name}" ${opts.required?'required':''}>${opts.options}</select></label>`;if(type==='textarea')return `<label class="${opts.full?'full':''}">${label}<textarea name="${name}" ${opts.required?'required':''}>${esc(value)}</textarea></label>`;return `<label class="${opts.full?'full':''}">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${opts.required?'required':''}></label>`}
function projectForm(p={}){return `<div class="form-grid">${field('Project Name','projectName','text',p.projectName,{required:true})}${field('Client / Company','clientCompany','text',p.clientCompany,{required:true})}${field('Brand','brand','text',p.brand)}${field('Client PIC','clientPic','text',p.clientPic)}${field('Client Contact','clientContact','text',p.clientContact)}${field('PM','pm','select','',{options:userOptions(p.pm)})}${field('Project Type','projectType','select','',{options:['Upcoming Pitching','Upcoming Project','Ongoing Project','Completed','Cancelled'].map(x=>option(x,x,p.projectType)).join('')})}${field('Status','projectStatus','select','',{options:['New','On Progress','Waiting Client','Won','Lose','Completed','Cancelled'].map(x=>option(x,x,p.projectStatus)).join('')})}${field('Start Date','startDate','date',dateKey(p.startDate))}${field('End Date','endDate','date',dateKey(p.endDate))}${field('Location','location','text',p.location)}${field('Drive Link','driveFolder','url',p.driveFolder,{full:true})}${field('Description','description','textarea',p.description,{full:true})}</div>`}
function taskForm(t={},projectId=''){return `<div class="form-grid">${field('Project','projectId','select','',{required:true,options:projectOptions(t.projectId||projectId)})}${field('Task','taskName','text',t.taskName,{required:true})}${field('PIC','pic','select','',{required:true,options:userOptions(t.pic)})}${field('Deadline','deadline','date',dateKey(t.deadline),{required:true})}${field('Status','status','select','',{options:['Not Started','On Progress','Waiting','Completed','Blocked'].map(x=>option(x,x,t.status||'Not Started')).join('')})}${field('Priority','priority','select','',{options:['Low','Medium','High','Urgent'].map(x=>option(x,x,t.priority||'Medium')).join('')})}${field('Progress %','progress','number',t.progress||0)}${field('File Link','fileLink','url',t.fileLink)}${field('Latest Update','latestUpdate','textarea',t.latestUpdate,{full:true})}${field('Next Action','nextAction','textarea',t.nextAction,{full:true})}${field('Blocker','blocker','textarea',t.blocker,{full:true})}${field('Description','description','textarea',t.description,{full:true})}</div>`}
function selectedParticipantIds(m={}){try{const x=JSON.parse(m.participantIds||'[]');if(Array.isArray(x)&&x.length)return x.map(String)}catch(e){}const names=String(m.participants||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return state.users.filter(u=>names.includes(String(u.name).toLowerCase())).map(u=>String(u.userId))}
function participantChecklist(m={}){const selected=selectedParticipantIds(m);const src=state.users.length?state.users:[{userId:'MIMO',name:'MIMO'},{userId:'IBNU',name:'Ibnu'},{userId:'ROSSY',name:'Rossy'},{userId:'ADEL',name:'Adel'},{userId:'NAY',name:'Nay'},{userId:'AGUNG',name:'Om Agung'},{userId:'EKI',name:'Eki'},{userId:'ALFA',name:'Pak Alfa'}];return `<div class="full"><div class="field-title">Participants</div><div class="participant-grid">${src.filter(u=>String(u.active)!=='false').map(u=>`<label class="check-card"><input type="checkbox" name="participantIds" value="${esc(u.userId)}" ${selected.includes(String(u.userId))?'checked':''}><span>${esc(u.name)}</span></label>`).join('')}</div></div>`}
function meetingForm(m={},projectId=''){return `<div class="form-grid">${field('Project','projectId','select','',{required:true,options:projectOptions(m.projectId||projectId)})}${field('Title','title','text',m.title,{required:true})}${field('Date','date','date',dateKey(m.date),{required:true})}${field('Start','startTime','time',timeKey(m.startTime),{required:true})}${field('End','endTime','time',timeKey(m.endTime))}${field('Location','location','text',m.location)}${field('Meeting Type','meetingType','select','',{options:['Internal','Client','Vendor','Survey','Briefing','Review','Other'].map(x=>option(x,x,m.meetingType)).join('')})}${field('Status','status','select','',{options:['Scheduled','Rescheduled','Completed','Cancelled'].map(x=>option(x,x,m.status||'Scheduled')).join('')})}<label class="toggle-card full"><input type="checkbox" name="alfaRequired" ${String(m.alfaRequired).toLowerCase()==='true'?'checked':''}><span><strong>Pak Alfa Required</strong><small>Aktifkan agar meeting otomatis masuk ke Alfa's Schedule.</small></span></label>${participantChecklist(m)}${field('Agenda','agenda','textarea',m.agenda,{full:true})}</div>`}
function meetingPayload(data,form){const ids=[...form.querySelectorAll('input[name="participantIds"]:checked')].map(x=>x.value);return {...data,participantIds:JSON.stringify(ids),alfaRequired:!!form.querySelector('input[name="alfaRequired"]')?.checked}}
function bindAlfaToggle(){setTimeout(()=>{const toggle=document.querySelector('input[name="alfaRequired"]');if(!toggle)return;toggle.onchange=()=>{if(!toggle.checked)return;const alfa=state.users.find(u=>String(u.name||'').toLowerCase().includes('alfa')||String(u.role||'').toUpperCase().includes('LEADER'));if(alfa){const cb=document.querySelector(`input[name="participantIds"][value="${CSS.escape(String(alfa.userId))}"]`);if(cb)cb.checked=true}}},0)}
function budgetForm(b={},projectId=''){return `<div class="form-grid">${field('Project','projectId','select','',{required:true,options:projectOptions(b.projectId||projectId)})}${field('Approved Quotation','approvedQuotation','number',b.approvedQuotation||0,{required:true})}${field('Planned Costing','plannedCosting','number',b.plannedCosting||0,{required:true})}${field('Actual Costing','actualCosting','number',b.actualCosting||0,{required:true})}</div>`}
function openMOM(meeting){const actionRow=(i=0)=>`<div class="action-row"><label class="action-name">Action<input name="action_${i}" placeholder="Contoh: Submit revised quotation"></label><label>PIC<select name="pic_${i}">${userOptions()}</select></label><label>Deadline<input name="deadline_${i}" type="date"></label><button type="button" class="btn small" data-remove-action>✕</button></div>`;openModal('MOM · '+meeting.title,`<div class="form-grid">${field('Discussion','discussion','textarea','',{full:true,required:true})}${field('Decision','decision','textarea','',{full:true})}${field('Client Request','clientRequest','textarea','',{full:true})}${field('MOM / File Link','attachmentLink','url','',{full:true})}</div><hr class="hr"><div class="section-head"><h3>Action Items</h3><button type="button" id="addActionBtn" class="btn primary small">+ Action</button></div><div id="actionRows" class="inline-list">${actionRow(0)}</div>`,async(data,form)=>{const mom=await API.call('createMOM',{meetingId:meeting.meetingId,discussion:data.discussion,decision:data.decision,clientRequest:data.clientRequest,attachmentLink:data.attachmentLink});const actions=[];[...form.querySelectorAll('[name^="action_"]')].forEach(el=>{const i=el.name.split('_')[1],actionItem=el.value.trim();if(actionItem)actions.push({momId:mom.momId,actionItem,pic:form.querySelector(`[name="pic_${i}"]`).value,deadline:form.querySelector(`[name="deadline_${i}"]`).value})});for(const a of actions)await API.call('createTaskFromMOM',a)});let i=1;setTimeout(()=>{$('#addActionBtn').onclick=()=>{$('#actionRows').insertAdjacentHTML('beforeend',actionRow(i++));bindRemoveActions()};bindRemoveActions()},0)}
function bindRemoveActions(){$$('[data-remove-action]').forEach(b=>b.onclick=()=>b.closest('.action-row').remove())}
async function viewMOM(meetingId){try{const mom=await API.call('getMOMByMeeting',{meetingId});if(!mom)return alert('MOM belum ditemukan');openModal('MOM',`<div class="summary-box"><strong>Decision</strong><p>${esc(mom.decision||'-')}</p></div><p><strong>Discussion</strong><br>${esc(mom.discussion||'-')}</p><p><strong>Client Request</strong><br>${esc(mom.clientRequest||'-')}</p>${mom.attachmentLink?`<p><a class="link" target="_blank" rel="noopener" href="${esc(mom.attachmentLink)}">Buka MOM File ↗</a></p>`:''}`,async()=>{})}catch(e){alert(e.message)}}
function bindDynamicActions(){
  $$('[data-edit-task]').forEach(b=>b.onclick=()=>{const t=[...state.tasks,...state.allTasks].find(x=>x.taskId===b.dataset.editTask);if(!t)return;openModal('Update Task',taskForm(t),d=>API.call('updateTask',{...d,taskId:t.taskId,progress:Number(d.progress||0)}))});
  $$('[data-create-mom]').forEach(b=>b.onclick=()=>{const m=state.meetings.find(x=>x.meetingId===b.dataset.createMom);if(m)openMOM(m)});
  $$('[data-view-mom]').forEach(b=>b.onclick=()=>viewMOM(b.dataset.viewMom));
  $$('[data-add-task-project]').forEach(b=>b.onclick=()=>openModal('Task Baru',taskForm({},b.dataset.addTaskProject),d=>API.call('createTask',{...d,progress:Number(d.progress||0)})));
  $$('[data-add-meeting-project]').forEach(b=>b.onclick=()=>{openModal('Meeting Baru',meetingForm({},b.dataset.addMeetingProject),(d,f)=>API.call('createMeeting',meetingPayload(d,f)));bindAlfaToggle()});
  $$('[data-edit-meeting]').forEach(b=>b.onclick=()=>{const m=state.meetings.find(x=>x.meetingId===b.dataset.editMeeting);if(!m)return;openModal('Edit / Reschedule Meeting',meetingForm(m),(d,f)=>API.call('updateMeeting',{...meetingPayload(d,f),meetingId:m.meetingId}));bindAlfaToggle()});
  $$('[data-complete-meeting]').forEach(b=>b.onclick=async()=>{const m=state.meetings.find(x=>x.meetingId===b.dataset.completeMeeting);if(!m)return;try{await API.call('updateMeeting',{meetingId:m.meetingId,status:'Completed',participantIds:m.participantIds||'[]',participants:m.participants||'',alfaRequired:String(m.alfaRequired).toLowerCase()==='true'});await refreshAll();const latest=state.meetings.find(x=>x.meetingId===m.meetingId)||m;openMOM(latest)}catch(e){alert(e.message)}});
  $$('[data-cancel-meeting]').forEach(b=>b.onclick=async()=>{if(!confirm('Batalkan meeting ini?'))return;const m=state.meetings.find(x=>x.meetingId===b.dataset.cancelMeeting);if(!m)return;try{await API.call('updateMeeting',{meetingId:m.meetingId,status:'Cancelled',participantIds:m.participantIds||'[]',participants:m.participants||'',alfaRequired:String(m.alfaRequired).toLowerCase()==='true'});toast('Meeting dibatalkan');await refreshAll()}catch(e){alert(e.message)}});
  $$('[data-budget-project]').forEach(b=>b.onclick=()=>{const old=state.budget.find(x=>x.projectId===b.dataset.budgetProject)||{};openModal('Update Budget',budgetForm(old,b.dataset.budgetProject),d=>API.call('updateBudget',d))})
}
$('#newProjectBtn').onclick=()=>openModal('Project Baru',projectForm(),d=>API.call('createProject',d));
$('#editProjectBtn').onclick=()=>{if(!state.selectedProject)return;openModal('Edit Project',projectForm(state.selectedProject),d=>API.call('updateProject',{...d,projectId:state.selectedProject.projectId}))};
$('#newTaskBtn').onclick=()=>openModal('Task Baru',taskForm(),d=>API.call('createTask',{...d,progress:Number(d.progress||0)}));
$('#newMeetingBtn').onclick=()=>{openModal('Meeting Baru',meetingForm(),(d,f)=>API.call('createMeeting',meetingPayload(d,f)));bindAlfaToggle()};
$('#newBudgetBtn').onclick=()=>openModal('Update Budget',budgetForm(),d=>API.call('updateBudget',d));
$('#newDailyBtn').onclick=()=>openModal('Daily Update',`<div class="form-grid">${field('Project','projectId','select','',{required:true,options:projectOptions()})}${field('Task ID (optional)','taskId','text','')}${field('Update Hari Ini','update','textarea','',{full:true,required:true})}${field('Next Action','nextAction','textarea','',{full:true})}${field('Blocker','blocker','textarea','',{full:true})}${field('Attachment / Link','attachment','url','',{full:true})}</div>`,d=>API.call('createDailyUpdate',d));
$('#newUserBtn').onclick=()=>openModal('User Baru',`<div class="form-grid">${field('Nama','name','text','',{required:true})}${field('Email','email','email','',{required:true})}${field('Phone','phone','text','')}${field('Role','role','select','',{options:['PM','ADMIN','TALENT','LOGISTIC','PERMITTER','LEADER'].map(x=>option(x,x)).join('')})}${field('Temporary Password','password','text','ChangeMe123!',{required:true})}</div>`,d=>API.call('createUser',d));
$('#changePasswordBtn').onclick=()=>openModal('Change Password',`<div class="form-grid">${field('Current Password','currentPassword','password','',{required:true})}${field('New Password','newPassword','password','',{required:true})}</div>`,d=>API.call('changePassword',d));
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});boot();
