const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,dashboard:null,projects:[],tasks:[],meetings:[],budget:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=v=>v?new Date(v).toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'-';
const isOverdue=t=>t.deadline&&t.status!=='Completed'&&new Date(t.deadline)<new Date(new Date().toDateString());

function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===page));}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));

async function boot(){if(!APP_CONFIG.API_URL.startsWith('http')) return;const token=localStorage.getItem(APP_CONFIG.TOKEN_KEY);if(!token)return;try{state.user=await API.call('getCurrentUser');await enterApp();}catch(e){localStorage.removeItem(APP_CONFIG.TOKEN_KEY)}}

$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='Memeriksa...';try{const d=await API.call('authenticateUser',{email:$('#email').value.trim(),password:$('#password').value});localStorage.setItem(APP_CONFIG.TOKEN_KEY,d.token);state.user=d.user;await enterApp();}catch(err){$('#loginMsg').textContent='Login gagal: '+err.message}};
$('#logoutBtn').onclick=async()=>{try{await API.call('logout')}catch(e){}localStorage.removeItem(APP_CONFIG.TOKEN_KEY);location.reload()};

async function enterApp(){ $('#loginView').classList.add('hidden');$('#mainView').classList.remove('hidden');$('#welcomeText').textContent='Halo, '+state.user.name;$('#userRole').textContent=state.user.role;await refreshAll(); }
async function refreshAll(){try{[state.dashboard,state.projects,state.tasks,state.meetings,state.budget]=await Promise.all([API.call('getDashboard'),API.call('getProjects'),API.call('getMyTasks'),API.call('getMeetings'),API.call('getBudget')]);render();}catch(e){alert('Gagal memuat data: '+e.message)}}
function render(){renderMetrics();renderProjects();renderTasks();renderMeetings();renderBudget();renderActivity();renderSchedule();}
function renderMetrics(){const d=state.dashboard||{};const items=[['Project',d.totalProjects||0],['My Tasks',d.myTasks||0],['Overdue',d.overdueTasks||0,true],['MOM Pending',d.momPending||0,true]];$('#metrics').innerHTML=items.map(x=>`<div class="metric ${x[2]&&x[1]>0?'attn':''}"><span>${esc(x[0])}</span><br><strong>${x[1]}</strong></div>`).join('');$('#homeTasks').innerHTML=state.tasks.slice(0,4).map(taskCard).join('')||empty('Belum ada task.');const today=new Date().toISOString().slice(0,10);$('#todayMeetings').innerHTML=state.meetings.filter(m=>String(m.date).slice(0,10)===today).map(meetingCard).join('')||empty('Tidak ada meeting hari ini.');}
function projectCard(p){return `<div class="card"><div class="row"><div><strong>${esc(p.projectName)}</strong><div class="muted">${esc(p.clientCompany)} · ${esc(p.brand)}</div></div><span class="badge">${esc(p.projectStatus)}</span></div><p class="muted">PM: ${esc(p.pm)} · ${fmtDate(p.startDate)} — ${fmtDate(p.endDate)}</p></div>`}
function taskCard(t){const overdue=isOverdue(t);return `<div class="card ${overdue?'attn':''}"><div class="row"><div><strong>${esc(t.taskName)}</strong><div class="muted">${esc(t.projectName)}</div></div><span class="badge">${overdue?'OVERDUE':esc(t.status)}</span></div><div class="muted">Deadline ${fmtDate(t.deadline)} · ${Number(t.progress||0)}%</div><div class="progress"><span style="width:${Math.max(0,Math.min(100,Number(t.progress||0)))}%"></span></div></div>`}
function meetingCard(m){return `<div class="card ${m.momStatus==='Pending'?'attn':''}"><div class="row"><div><strong>${esc(m.startTime||'')} ${esc(m.title)}</strong><div class="muted">${esc(m.projectName)} · ${esc(m.location)}</div></div><span class="badge">MOM ${esc(m.momStatus||'Pending')}</span></div><p class="muted">${fmtDate(m.date)} · ${esc(m.participants||'')}</p></div>`}
function empty(t){return `<div class="card"><span class="muted">${esc(t)}</span></div>`}
function renderProjects(){const q=($('#projectSearch').value||'').toLowerCase();const arr=state.projects.filter(p=>JSON.stringify(p).toLowerCase().includes(q));$('#projectList').innerHTML=arr.map(projectCard).join('')||empty('Project belum ada.');}
$('#projectSearch').oninput=renderProjects;
function renderTasks(){const filters=['All','Today','Overdue','On Progress','Waiting','Blocked','Completed'];$('#taskFilters').innerHTML=filters.map((x,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;let a=state.tasks;if(f==='Overdue')a=a.filter(isOverdue);else if(f!=='All'&&f!=='Today')a=a.filter(t=>t.status===f);else if(f==='Today'){const d=new Date().toISOString().slice(0,10);a=a.filter(t=>String(t.deadline).slice(0,10)===d)}$('#taskList').innerHTML=a.map(taskCard).join('')||empty('Tidak ada task.');});$('#taskList').innerHTML=state.tasks.map(taskCard).join('')||empty('Belum ada task.');}
function renderMeetings(){$('#meetingList').innerHTML=state.meetings.map(meetingCard).join('')||empty('Belum ada meeting.');}
function renderBudget(){$('#budgetList').innerHTML=state.budget.map(b=>`<div class="card ${['ALERT','OVER BUDGET'].includes(b.budgetStatus)?'attn':''}"><div class="row"><strong>${esc(b.projectName)}</strong><span class="badge">${esc(b.budgetStatus)}</span></div><p>Approved: Rp ${Number(b.approvedQuotation||0).toLocaleString('id-ID')}<br>Planned: Rp ${Number(b.plannedCosting||0).toLocaleString('id-ID')}<br>Actual: Rp ${Number(b.actualCosting||0).toLocaleString('id-ID')}</p></div>`).join('')||empty('Budget belum ada.');}
async function renderActivity(){try{const a=await API.call('getActivityLog');$('#activityList').innerHTML=a.slice(0,50).map(x=>`<div class="card"><strong>${esc(x.userName||x.user)}</strong><div>${esc(x.description)}</div><span class="muted">${esc(x.timestamp)}</span></div>`).join('')||empty('Belum ada activity.')}catch(e){$('#activityList').innerHTML=empty('Activity belum bisa dimuat.')}}
function renderSchedule(){const a=state.meetings.filter(m=>(m.participants||'').toLowerCase().includes('alfa')).sort((a,b)=>String(a.date+a.startTime).localeCompare(String(b.date+b.startTime)));$('#scheduleList').innerHTML=a.map(meetingCard).join('')||empty('Tidak ada jadwal Pak Alfa.');}
function openModal(title,fields,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<div class="form-grid">${fields.map(f=>`<label class="${f.full?'full':''}">${f.label}${f.type==='select'?`<select name="${f.name}">${f.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea name="${f.name}"></textarea>`:`<input name="${f.name}" type="${f.type||'text'}" ${f.required?'required':''}></label>`).join('')}</div>`;const dlg=$('#modal');dlg.showModal();$('#modalForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());try{$('#modalSave').disabled=true;await onSave(data);dlg.close();await refreshAll()}catch(err){alert(err.message)}finally{$('#modalSave').disabled=false}}}
$('#newProjectBtn').onclick=()=>openModal('Project Baru',[{label:'Project Name',name:'projectName',required:true},{label:'Client / Company',name:'clientCompany',required:true},{label:'Brand',name:'brand'},{label:'PM',name:'pm',type:'select',options:['MIMO','Ibnu','Rossy']},{label:'Project Type',name:'projectType',type:'select',options:['Upcoming Pitching','Upcoming Project','Ongoing Project']},{label:'Status',name:'projectStatus',type:'select',options:['New','On Progress','Waiting Client','Won','Lose','Completed']},{label:'Start Date',name:'startDate',type:'date'},{label:'End Date',name:'endDate',type:'date'},{label:'Drive Link',name:'driveFolder',full:true}],d=>API.call('createProject',d));
$('#newTaskBtn').onclick=()=>openModal('Task Baru',[{label:'Project ID',name:'projectId',required:true},{label:'Task',name:'taskName',required:true},{label:'PIC',name:'pic',required:true},{label:'Deadline',name:'deadline',type:'date',required:true},{label:'Status',name:'status',type:'select',options:['Not Started','On Progress','Waiting','Completed','Blocked']},{label:'Priority',name:'priority',type:'select',options:['Low','Medium','High','Urgent']},{label:'Description',name:'description',type:'textarea',full:true}],d=>API.call('createTask',d));
$('#newMeetingBtn').onclick=()=>openModal('Meeting Baru',[{label:'Project ID',name:'projectId',required:true},{label:'Title',name:'title',required:true},{label:'Date',name:'date',type:'date',required:true},{label:'Start',name:'startTime',type:'time',required:true},{label:'End',name:'endTime',type:'time'},{label:'Location',name:'location'},{label:'Participants',name:'participants',full:true},{label:'Agenda',name:'agenda',type:'textarea',full:true}],d=>API.call('createMeeting',d));
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});boot();
