function hash_(password,salt){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,password+salt,Utilities.Charset.UTF_8);return bytes.map(function(b){var x=(b<0?b+256:b).toString(16);return x.length===1?'0'+x:x}).join('')}
function seedAdmin_(){if(listRows_('USERS').length)return;var salt=Utilities.getUuid();append_('USERS',{userId:'USR-ADMIN',name:'MIMO',email:'CHANGE_ME@example.com',passwordHash:hash_('ChangeMe123!',salt),salt:salt,role:'PM',active:true,createdAt:new Date(),updatedAt:new Date()})}
function authenticateUser(p){var email=String(p.email||'').trim().toLowerCase(),users=listRows_('USERS');var u=users.find(function(x){return String(x.email).toLowerCase()===email&&String(x.active).toLowerCase()!=='false'});if(!u||hash_(String(p.password||''),u.salt)!==u.passwordHash)throw new Error('Email atau password salah');var token=Utilities.getUuid()+Utilities.getUuid();PropertiesService.getScriptProperties().setProperty('SESSION_'+token,JSON.stringify({userId:u.userId,expires:Date.now()+APP.SESSION_HOURS*3600000}));log_(u,'LOGIN','AUTH',u.userId,'User login');return{token:token,user:safeUser_(u)}}
function requireSession_(token){var raw=PropertiesService.getScriptProperties().getProperty('SESSION_'+token);if(!raw)throw new Error('Session expired');var s=JSON.parse(raw);if(Date.now()>s.expires){PropertiesService.getScriptProperties().deleteProperty('SESSION_'+token);throw new Error('Session expired')}var u=getById_('USERS','userId',s.userId);if(!u||String(u.active).toLowerCase()==='false')throw new Error('User inactive');return safeUser_(u)}
function safeUser_(u){return{userId:u.userId,name:u.name,email:u.email,role:u.role,phone:u.phone,active:u.active}}
function logout_(token){PropertiesService.getScriptProperties().deleteProperty('SESSION_'+token);return true}
function isManager_(u){var r=String(u.role||'').toUpperCase();return ['PM','ADMIN','LEADER','OWNER','CEO'].some(function(x){return r.indexOf(x)>=0})}
function isAdmin_(u){var r=String(u.role||'').toUpperCase();return ['ADMIN','LEADER','OWNER','CEO'].some(function(x){return r.indexOf(x)>=0})}
function changePassword_(p,user){if(!p.currentPassword||!p.newPassword||String(p.newPassword).length<8)throw new Error('Password baru minimal 8 karakter');var full=getById_('USERS','userId',user.userId);if(!full||hash_(String(p.currentPassword),full.salt)!==full.passwordHash)throw new Error('Password lama salah');var salt=Utilities.getUuid();updateEntity_('USERS','userId',{userId:user.userId,salt:salt,passwordHash:hash_(String(p.newPassword),salt)},user);return true}
function getUsers_(user){if(!isAdmin_(user)&&!isManager_(user))throw new Error('Tidak memiliki akses');return listRows_('USERS').map(safeUser_)}
function createUser_(p,user){if(!isAdmin_(user))throw new Error('Hanya Admin/Leader yang dapat menambah user');if(!p.name||!p.email||!p.password)throw new Error('Nama, email, password wajib');var exists=listRows_('USERS').some(function(x){return String(x.email).toLowerCase()===String(p.email).toLowerCase()});if(exists)throw new Error('Email sudah terdaftar');var salt=Utilities.getUuid();var o={name:p.name,email:String(p.email).trim().toLowerCase(),phone:p.phone||'',role:p.role||'STAFF',active:true,salt:salt,passwordHash:hash_(String(p.password),salt)};return safeUser_(createEntity_('USERS','userId','USR',o,user))}
