function doGet(){return json_({success:true,data:{service:'DOTSIXTWOO API',version:'2.0.0'}})}
function doPost(e){try{var req=JSON.parse((e.postData&&e.postData.contents)||'{}');var action=req.action||'';var payload=req.payload||{};var token=req.token||'';var publicActions=['authenticateUser'];var user=null;if(publicActions.indexOf(action)===-1)user=requireSession_(token);var routes={
authenticateUser:function(){return authenticateUser(payload)},getCurrentUser:function(){return user},logout:function(){return logout_(token)},changePassword:function(){return changePassword_(payload,user)},getUsers:function(){return getUsers_(user)},createUser:function(){return createUser_(payload,user)},
getDashboard:function(){return getDashboard_(user)},
getProjects:function(){return listRows_('PROJECTS')},getProject:function(){return getById_('PROJECTS','projectId',payload.projectId)},createProject:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses membuat project');return createProject_(payload,user)},updateProject:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses mengubah project');return updateEntity_('PROJECTS','projectId',payload,user)},
getTasks:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses semua task');return listRows_('TASKS')},getMyTasks:function(){return listRows_('TASKS').filter(function(x){return String(x.picEmail||'').toLowerCase()===String(user.email).toLowerCase()||String(x.pic||'').toLowerCase()===String(user.name).toLowerCase()})},createTask:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses membuat task');return createTask_(payload,user)},updateTask:function(){return updateTask_(payload,user)},
getMeetings:function(){return listRows_('MEETINGS')},createMeeting:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses membuat meeting');return createMeeting_(payload,user)},updateMeeting:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses');return updateEntity_('MEETINGS','meetingId',payload,user)},
createMOM:function(){return createMOM_(payload,user)},getMOMByMeeting:function(){return getMOMByMeeting_(payload.meetingId)},updateMOM:function(){return updateEntity_('MOM','momId',payload,user)},createTaskFromMOM:function(){return createTaskFromMOM_(payload,user)},
getBudget:function(){return getBudget_()},updateBudget:function(){if(!isManager_(user))throw new Error('Tidak memiliki akses budget');return updateBudget_(payload,user)},
getDocuments:function(){return listRows_('DOCUMENTS')},createDocument:function(){return createEntity_('DOCUMENTS','documentId','DOC',payload,user)},
getActivityLog:function(){return listRows_('ACTIVITY_LOG').reverse()},getNotifications:function(){return listRows_('NOTIFICATIONS').filter(function(x){return String(x.userId)===String(user.userId)&&!x.readAt}).reverse()},markNotificationRead:function(){return updateEntity_('NOTIFICATIONS','notificationId',{notificationId:payload.notificationId,readAt:new Date()},user)},
createDailyUpdate:function(){payload.pic=user.name;payload.date=new Date();payload.time=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'HH:mm');return createEntity_('DAILY_UPDATES','updateId','U',payload,user)},getDailyUpdates:function(){var rows=listRows_('DAILY_UPDATES');return isManager_(user)?rows:rows.filter(function(x){return String(x.pic).toLowerCase()===String(user.name).toLowerCase()})}
};if(!routes[action])throw new Error('Unknown action: '+action);return json_({success:true,data:routes[action]()})}catch(err){return json_({success:false,error:String(err.message||err)})}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
