var SCHEMA={USERS:['userId','name','email','passwordHash','salt','role','active','phone','createdAt','updatedAt'],PROJECTS:['projectId','projectName','dateReceived','clientCompany','brand','clientPic','clientContact','projectType','projectStatus','pm','startDate','endDate','location','description','driveFolder','createdBy','createdAt','updatedBy','updatedAt'],TASKS:['taskId','projectId','projectName','taskName','pic','picEmail','priority','deadline','status','progress','description','latestUpdate','nextAction','blocker','fileLink','momId','createdBy','createdAt','updatedBy','updatedAt'],MEETINGS:['meetingId','projectId','projectName','title','date','startTime','endTime','location','meetingType','participants','agenda','status','momStatus','createdBy','createdAt','updatedBy','updatedAt','participantIds','alfaRequired'],MOM:['momId','meetingId','projectId','projectName','meetingDate','participants','discussion','decision','clientRequest','attachmentLink','createdBy','createdAt','updatedBy','updatedAt'],MOM_ACTIONS:['actionId','momId','projectId','actionItem','pic','deadline','taskId','status'],DAILY_UPDATES:['updateId','projectId','taskId','pic','date','time','update','nextAction','blocker','attachment','createdBy','createdAt'],BUDGET:['budgetId','projectId','projectName','approvedQuotation','plannedCosting','actualCosting','remainingBudget','variance','estimatedProfit','marginPercent','budgetUsagePercent','budgetStatus','updatedBy','updatedAt'],DOCUMENTS:['documentId','projectId','taskId','name','type','version','link','createdBy','createdAt'],ACTIVITY_LOG:['logId','timestamp','userId','userName','action','module','recordId','description'],NOTIFICATIONS:['notificationId','userId','type','title','message','recordId','createdAt','readAt','deliveryStatus'],SETTINGS:['key','value','updatedAt']};
function setupSystem(){var ss=db_();Object.keys(SCHEMA).forEach(function(name){var sh=ss.getSheetByName(name)||ss.insertSheet(name);var headers=SCHEMA[name];if(sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]);else sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1)});seedAdmin_();return 'Setup complete'}
function sheet_(name){var s=db_().getSheetByName(name);if(!s)throw new Error('Sheet '+name+' not found. Run setupSystem().');return s}
function listRows_(name){var sh=sheet_(name),v=sh.getDataRange().getValues();if(v.length<2)return[];var h=v[0];return v.slice(1).filter(function(r){return r.some(function(x){return x!==''})}).map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i]});return o})}
function append_(name,obj){var sh=sheet_(name),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];sh.appendRow(h.map(function(k){return obj[k]!==undefined?obj[k]:''}));return obj}
function getById_(name,key,id){var all=listRows_(name);for(var i=0;i<all.length;i++)if(String(all[i][key])===String(id))return all[i];return null}
function updateEntity_(name,key,payload,user){var sh=sheet_(name),v=sh.getDataRange().getValues(),h=v[0],idx=h.indexOf(key);if(idx<0)throw new Error('ID field not found');for(var r=1;r<v.length;r++){if(String(v[r][idx])===String(payload[key])){Object.keys(payload).forEach(function(k){var c=h.indexOf(k);if(c>=0)sh.getRange(r+1,c+1).setValue(payload[k])});var ub=h.indexOf('updatedBy'),ua=h.indexOf('updatedAt');if(ub>=0)sh.getRange(r+1,ub+1).setValue(user.name);if(ua>=0)sh.getRange(r+1,ua+1).setValue(new Date());log_(user,'UPDATE',name,payload[key],name+' updated');return getById_(name,key,payload[key])}}throw new Error('Record not found')}
function nextId_(prefix){return prefix+'-'+Utilities.getUuid().split('-')[0].toUpperCase()}
function createEntity_(name,key,prefix,payload,user){var o={};Object.keys(payload).forEach(function(k){o[k]=payload[k]});o[key]=nextId_(prefix);o.createdBy=user.name;o.createdAt=new Date();o.updatedBy=user.name;o.updatedAt=new Date();append_(name,o);log_(user,'CREATE',name,o[key],name+' created');return o}
