function activeUsers_(){return listRows_('USERS').filter(function(u){return String(u.active).toLowerCase()!=='false'})}
function findAlfaUser_(){var users=activeUsers_();return users.find(function(u){return String(u.name||'').toLowerCase().indexOf('alfa')>=0||String(u.role||'').toUpperCase().indexOf('LEADER')>=0})||null}
function parseParticipantIds_(value){if(!value)return[];if(Array.isArray(value))return value;try{var a=JSON.parse(value);return Array.isArray(a)?a:[]}catch(e){return String(value).split(',').map(function(x){return x.trim()}).filter(Boolean)}}
function normalizeMeetingParticipants_(p){var ids=parseParticipantIds_(p.participantIds),alfa=findAlfaUser_();if(String(p.alfaRequired).toLowerCase()==='true'&&alfa&&ids.indexOf(alfa.userId)<0)ids.push(alfa.userId);var users=activeUsers_(),names=[];ids.forEach(function(id){var u=users.find(function(x){return String(x.userId)===String(id)});if(u&&names.indexOf(u.name)<0)names.push(u.name)});if(!ids.length&&p.participants){String(p.participants).split(',').map(function(x){return x.trim()}).filter(Boolean).forEach(function(n){if(names.indexOf(n)<0)names.push(n)})}p.participantIds=JSON.stringify(ids);p.participants=names.join(', ');p.alfaRequired=String(p.alfaRequired).toLowerCase()==='true';return p}
function createMeeting_(p,user){if(!p.projectId||!p.title||!p.date||!p.startTime)throw new Error('Project, title, tanggal dan jam wajib');var project=getById_('PROJECTS','projectId',p.projectId);if(project)p.projectName=project.projectName;p.status=p.status||'Scheduled';p.momStatus=p.status==='Completed'?'Pending':(p.status==='Cancelled'?'N/A':'Waiting');normalizeMeetingParticipants_(p);var m=createEntity_('MEETINGS','meetingId','M',p,user);log_(user,'CREATE','MEETING',m.meetingId,'Meeting created');return m}
function updateMeeting_(p,user){var current=getById_('MEETINGS','meetingId',p.meetingId);if(!current)throw new Error('Meeting tidak ditemukan');normalizeMeetingParticipants_(p);var mom=getMOMByMeeting_(p.meetingId);if(p.status==='Completed'&&!mom)p.momStatus='Pending';else if(p.status==='Cancelled'&&!mom)p.momStatus='N/A';else if(!mom&&(p.status==='Scheduled'||p.status==='Rescheduled'))p.momStatus='Waiting';return updateEntity_('MEETINGS','meetingId',p,user)}
function getAlfaSchedule_(){var alfa=findAlfaUser_(),aid=alfa?String(alfa.userId):'';return listRows_('MEETINGS').filter(function(m){if(String(m.status)==='Cancelled')return false;var ids=parseParticipantIds_(m.participantIds);return (aid&&ids.indexOf(aid)>=0)||String(m.participants||'').toLowerCase().indexOf('alfa')>=0||String(m.alfaRequired).toLowerCase()==='true'}).map(meetingForClient_)}

// MVP v2.3: normalize Sheet Date/Time values before sending them to the browser.
// Google Sheets may return a time cell as a Date anchored at 1899-12-30.
function appTimeZone_(){try{return db_().getSpreadsheetTimeZone()||Session.getScriptTimeZone()||'Asia/Jakarta'}catch(e){return Session.getScriptTimeZone()||'Asia/Jakarta'}}
function dateForClient_(v){if(!v)return '';if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v))return Utilities.formatDate(v,appTimeZone_(),'yyyy-MM-dd');var s=String(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s.slice(0,10)))return s.slice(0,10);var d=new Date(v);return isNaN(d)?s:Utilities.formatDate(d,appTimeZone_(),'yyyy-MM-dd')}
function timeForClient_(v){if(!v)return '';var s=String(v),m=s.match(/^(\d{1,2}):(\d{2})/);if(m)return ('0'+m[1]).slice(-2)+':'+m[2];if(Object.prototype.toString.call(v)==='[object Date]'&&!isNaN(v))return Utilities.formatDate(v,appTimeZone_(),'HH:mm');var d=new Date(v);return isNaN(d)?s.slice(0,5):Utilities.formatDate(d,appTimeZone_(),'HH:mm')}
function meetingForClient_(m){var x={};Object.keys(m||{}).forEach(function(k){x[k]=m[k]});x.date=dateForClient_(x.date);x.startTime=timeForClient_(x.startTime);x.endTime=timeForClient_(x.endTime);return x}
function getMeetings_(){return listRows_('MEETINGS').map(meetingForClient_)}
